spring:
  application:
    name: Pumpit

  profiles:
    active: local  # 기본 실행 프로파일 (local, dev, prod)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      jdbc:
        time_zone: UTC
      hibernate:
        format_sql: true
        show_sql: true

server:
  error:
    include-message: always  # 에러 메시지 포함

jwt:
  token:
    secret: dlfjgrptlzmfltdmf1gksekauschlth32wkdltkddlaqehlfrjdkdu
    access:
      expiration: 86400000  # 1 day milliseconds
    refresh:
      expiration: 604800000  # 7 days milliseconds

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

security:
  aes:
    key: TOP_!@22_BIG_SECRET_DD_KEY_^^&_OK